runtime: php81
env: standard
runtime_config:
  document_root: .
# for detecting static files in the public folder
handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  APP_ENV: production
  APP_KEY: base64:6qS4VOsj3gT9qQacx2snIVYtyZUW1ec3i8mDNyVNcxc=
  # Agrega otras variables de entorno según sea necesario
